# PUIUX Click - pnpm Workspace Configuration

packages:
  # Main applications
  - 'apps/*'

  # Shared packages
  - 'packages/*'

  # Exclude common directories
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!**/build/**'
